name = "ClustalO"
uuid = "47afe195-f837-4f54-902b-01e24dcbc80d"
authors = ["Michael Persico <michael.a.persico@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
